export type ItemKey = "potion" | "hiPotion" | "megaPotion";
export type WeaponKey = "woodSword" | "ironSword" | "steelSword" | "mythrilBlade";
export type ArmorKey = "clothArmor" | "chainMail" | "knightArmor" | "dragonArmor";
export type SkillKey = "spark" | "iceShard" | "thunderLance" | "meteorBreak";

/** Remaining skill cooldown per ability (full turns tick down after each enemy action). */
export type SkillCooldownMap = Record<SkillKey, number>;

export type HairStyle = "short" | "spiky" | "long" | "bald";

export interface PlayerAppearance {
  skin: string;
  hair: string;
  hairStyle: HairStyle;
  outfit: string;
  pants: string;
}

export interface PlayerState {
  name: string;
  level: number;
  xp: number;
  xpToNext: number;
  gold: number;
  maxHp: number;
  hp: number;
  attack: number;
  defense: number;
  speed: number;
  weapon: WeaponKey;
  armor: ArmorKey;
  items: Record<ItemKey, number>;
  map: string;
  x: number;
  y: number;
  monstersDefeated: number;
  bountyTier: number;
  bossDefeated: boolean;
  appearance: PlayerAppearance;
  /** True once the player has gone through the character creation screen. */
  hasCreatedCharacter: boolean;
  /** True once the player has purchased the Town Map at a shop. One-time buy. */
  hasTownMap: boolean;
}

/** Distinct overworld regions with their own flora, palette, and monster pools. */
export type BiomeKind = "meadow" | "forest" | "desert" | "swamp" | "tundra";

export interface EnemyDefinition {
  id: string;
  name: string;
  maxHp: number;
  attack: number;
  defense: number;
  speed: number;
  xpReward: number;
  goldReward: number;
  minLevel: number;
  baseWeight: number;
  weightGrowthPerLevel: number;
  maxWeight: number;
  /**
   * Biomes this enemy can spawn in. Omit (or empty) to allow every biome.
   * Used to gate encounter pools regionally.
   */
  biomes?: BiomeKind[];
  /** Explicit body-shape override (for palette variants reusing an existing model). */
  bodyShape?: MonsterBodyShape;
  /** Optional color overrides applied to the 3D model. */
  customColors?: { primary?: string; accent?: string };
}

/** Body shapes available to both built-in and UGC monsters. */
export type MonsterBodyShape =
  | "slime"
  | "bat"
  | "goblin"
  | "wolf"
  | "wraith"
  | "drake"
  | "spider"
  | "scorpion";

export interface EnemyState extends EnemyDefinition {
  hp: number;
}

export type BattlePhase = "idle" | "playerTurn" | "enemyTurn" | "won" | "lost" | "escaped";

export interface BattleState {
  inBattle: boolean;
  phase: BattlePhase;
  log: string[];
  enemy: EnemyState | null;
  skillCooldowns: SkillCooldownMap;
}

export interface WorldState {
  inTown: boolean;
  canHeal: boolean;
  canShop: boolean;
  canTrain: boolean;
  canGuild: boolean;
  canBoss: boolean;
  encounterRate: number;
  /** Random encounter rolls are skipped until this hits 0 (ticks down on each wilderness tile step). */
  encounterGraceSteps: number;
  /** Seed used to procedurally generate the active overworld. */
  worldSeed: number;
  /** Bumped every time the world is regenerated — used as a React render dependency. */
  worldVersion: number;
}

/** Shared fields for all marketplace-listed UGC creations. */
export interface UgcListing {
  listed: boolean;
  price: number;
  sales: number;
  /** Total gross gold the listing has generated (creator + tax). */
  grossEarned: number;
}

export interface UgcMonster extends UgcListing {
  id: string;
  name: string;
  bodyShape: MonsterBodyShape;
  colorPrimary: string;
  colorAccent: string;
  maxHp: number;
  attack: number;
  defense: number;
  speed: number;
  xpReward: number;
  goldReward: number;
  minLevel: number;
  createdAt: number;
}

export interface UgcWeapon extends UgcListing {
  id: string;
  name: string;
  attackBonus: number;
  color: string;
  createdAt: number;
}

export interface UgcArmor extends UgcListing {
  id: string;
  name: string;
  defenseBonus: number;
  color: string;
  createdAt: number;
}

/** Full UGC studio + marketplace state. */
export interface UgcState {
  monsters: UgcMonster[];
  weapons: UgcWeapon[];
  armor: UgcArmor[];
  /** Lifetime gross gold generated by all listings. */
  totalGross: number;
  /** Lifetime 75% creator share paid into the player's wallet. */
  totalNet: number;
  /** Lifetime 25% platform tax withheld. */
  totalTax: number;
  totalSales: number;
}

/** Named chapter / stage the player is currently on. */
export type StoryStage =
  | "prologue"
  | "ch1_firstHunts"
  | "ch2_gearUp"
  | "ch3_wanderer"
  | "ch4_whispers"
  | "ch5_trials"
  | "ch6_titanAwaits"
  | "epilogue";

/** A record of a completed chapter, used by the in-game Journal. */
export interface StoryChapterRecord {
  stage: StoryStage;
  title: string;
  completedAt: number;
}

export interface StoryState {
  /** The chapter currently in progress (or "prologue"/"epilogue" for intro/outro). */
  stage: StoryStage;
  /** True once the player has dismissed the opening prologue modal. */
  prologueSeen: boolean;
  /** True once the player has dismissed the closing epilogue modal. */
  epilogueSeen: boolean;
  /** Total monsters the player has slain (battle victories). */
  monstersSlain: number;
  /** Unique biomes the player has stepped foot in. */
  biomesVisited: BiomeKind[];
  /** Unique enemy IDs the player has defeated at least once. */
  uniqueSpeciesDefeated: string[];
  /** True once the player has bought any weapon stronger than the starting wooden sword. */
  boughtBetterGear: boolean;
  /** True once the player has stood on the boss arena tile. */
  reachedBossArena: boolean;
  /** Chapters that have been completed, in order. */
  completed: StoryChapterRecord[];
  /**
   * Slot for a chapter transition UI to pick up — becomes the stage that was
   * just completed. The UI consumes it (via a store action) once it has
   * shown the banner, which resets this back to null.
   */
  pendingChapterToast: StoryStage | null;
}

export interface GameSnapshot {
  player: PlayerState;
  battle: BattleState;
  world: WorldState;
  eventLog: string[];
  ugc: UgcState;
  story: StoryState;
  /**
   * When false, persisted slot matches this snapshot (excluding the optional
   * trailing "Game saved." line that is written on the next save).
   */
  hasUnsavedChanges: boolean;
}
